### PR TITLE
Code fixes from develop to release/1.5

### PR DESCRIPTION
**Pull request by vikasrathee-cs**
Code fixes from develop to release/1.5

### CODE REVIEW

**Comment by greeshmaswaminathan** [comment]
Is the geo location commit intended to be here ?

**Comment by vikasrathee-cs** [comment]
> Is the geo location commit intended to be here ?

it is just a documentation change in md file.

**Review by greeshmaswaminathan — APPROVED** [review]

**Comment by snehalakshmisha** [comment]
https://github.com/data-integrations/salesforce/pull/138 - this PR needs to be part of release 1.5

**Comment by snehalakshmisha** [comment]
the release branch already contains the PR - https://github.com/data-integrations/salesforce/pull/138 that is required to be in v1.5. As long as we rebase and merge keeping these changes, we should be fine.

**Pull request merged**
